<#setting locale="en_US">
<#setting number_format="computer">
<#setting boolean_format="true,false" >

<#include "support/data_model/data-model_utils.ftl" >


<#import "support/MC_task/utils/pins_mng.ftl" as ns_pin>
<#import "support/ui.ftl" as ui >
<#import "support/fp.ftl" as fp>
<#import "config.ftl"     as config>
<#import "header.ftl"     as hh>

<#assign file_name = .current_template_name>
<@hh.header file_name>
    This file translates a Motor Control Workbench output file to a fully working STM32CubeMx project (ioc file).
</@hh.header>
<#--

-->
    <@ui.box "ioc file generated by ST MC-Workbench" />
    <#--<#include "support/utils.ftl" >-->
    <#include "support/data_model/known_values.ftl" >
    <#include "support/Definitions.ftl">
    <#include "support/data_model/expose_typed-defines_to_freemarker.ftl" >
    <#include "support/data_model/wb_def-Default_defines.ftl">
    <#include "support/data_model/expose_symplified_GPIO_to_freemarker.ftl" >
    <#import "support/conditional_task.ftl" as task >

<#--<#global WB_DRIVE_TYPE = WB_DRIVE_TYPE!"FOC">-->
<#--

-->
    <#import "ioc_seed/hw_info.ftl" as hw >
    <#global cpu   = hw.cpu   >
    <#global board = hw.board >
    <@ui.comment "wb_mcu = \"${cpu.name}\"" />
    <@ui.comment "board  = \"${board.name}\" - mcu = ${board.mcu}" />
<#-- -->
    <#import "ioc_seed/ioc_init.ftl" as ioc_init >
    <@task.task "IOC INIT" config.mcu!true>
        <@ioc_init.init_ioc hw />
    </@task.task>
    <#global DAC1 = DAC1!"DAC">

<@task.task "FORWARDs the WB generated #defines to MX" config.forward_defines_to_mx!true >
    <#import "support/data_model/forward_defines_to_mx.ftl" as mc_middleware >
    <@ui.boxed "ExtraMW_MotorControl & VP_MotorControl generated defines">
        <@mc_middleware.motorControl_IP_settings/>
    </@ui.boxed>
</@task.task>

<#-- --------------------------------------------------------------------------------------------------------------- -->
<#-- Introduce additional defines according the selected device                                                      -->
<#-- --------------------------------------------------------------------------------------------------------------- -->
<#include "support/device_name_mapping.ftl" >
<#--

-->

<#-- --------------------------------------------------------------------------------------------------------------- -->
<#-- Parameter conversions and Mc_Task                                                                               -->
<#-- --------------------------------------------------------------------------------------------------------------- -->
<#include "support/parameters_conversion/Parameters conversion.ftl" >


<#if  WB_DRIVE_TYPE=="SIX_STEP">
   <#-- <#include "6-step_task.ftl"/>-->
    <@ui.box "SIX_STEP is Not support in GENERATE but only in UPDATE mode" '' '.' />
<#else>
    <#include "foc_task.ftl"/>
</#if>

<#--
<#import "support/MC_task/MC_task.ftl" as mc_tasks>
<@mc_tasks.MC_tasks config />
-->

<#--

<#import "support/UI_tasks/UI_tasks.ftl" as ui_tasks>
<@ui_tasks.UI_tasks (config.ui)!{} />

<#import "support/PFC_tasks/PFC_tasks.ftl" as pfc_tasks>
<@pfc_tasks.PFC_tasks (config.pfc)!{} />

<#import "support/FreeRTOS/FreeRTOS_tasks.ftl" as FreeRTOS>
<@FreeRTOS.FreeRTOS_tasks />

-->


<#import "support/shared_ip/ip_overlap.ftl" as ip_ov>
<@ui.comment "Consolidated IPs" />

<@ip_ov.consolidated_IPs_settings />

<@ns_pin.used_Mcu_Pins />

<#import "support/MC_task/utils/ips_mng.ftl" as ns_ip>
<@ns_ip.used_Mcu_IPs />

<#import "support/MC_task/utils/cortexMx_mng.ftl" as ns_Cortex_ip>
<@ns_Cortex_ip.used_McuCortexMx_IPs />


<@task.task "FORWARDs the WB generated #defines to MX" config.forward_defines_to_mx!true >
<#import "support/data_model/forward_defines_to_mx.ftl" as mc_middleware >
    <@ui.boxed "ST Workbench generated defines">
        <@mc_middleware.export_ExtraMW false/>
    </@ui.boxed>
</@task.task>


<#import "support/hal_ll_drivers/driver_mng.ftl" as ns_dr>
<@ns_dr.apply_selected_driver ns_ip.ipDB()?keys />

<#import "support/MC_task/utils/user_constants.ftl" as mcu>
Mcu.UserConstants=${ mcu.serialize_collected_defines() }

<@task.task "...more" config.more!false>
    <#import "more.ftl" as more>
    <@more.do_more />
</@task.task>


